version: '3.8'

services:
  app:
    image: mnibor/academia-app:latest
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:  # Usa expose en lugar de ports para el contenedor interno
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monta tu configuración de Nginx
    ports:
      - "80:80"  # Expone el puerto 80 para acceso externo
    depends_on:
      - app  # Asegúrate de que Nginx espera a que el servicio app esté listo
